package com.naterbobber.darkerdepths.core.registries;

import com.naterbobber.darkerdepths.common.blocks.*;
import com.naterbobber.darkerdepths.common.blocks.material.DDMaterial;
import com.naterbobber.darkerdepths.core.DDRegistries;
import com.naterbobber.darkerdepths.core.DarkerDepths;

import net.minecraft.block.*;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialColor;
import net.minecraft.state.properties.BlockStateProperties;
import net.minecraftforge.common.ToolType;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.fml.common.Mod;

import java.util.function.ToIntFunction;

//<>

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class DDBlocks {
	public static final DDRegistries HELPER = DarkerDepths.REGISTRIES;

	//BUILDING BLOCKS
	public static final RegistryObject<Block> PETRIFIED_PLANKS 			= HELPER.registerBlock("petrified_planks", () -> new Block(Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(2.5f, 3.0f).harvestTool(ToolType.PICKAXE).harvestLevel(0).sound(SoundType.WOOD)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> PETRIFIED_LOG 			= HELPER.registerBlock("petrified_log", () -> new RotatedPillarBlock(Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(2.4f, 3.0f).harvestTool(ToolType.PICKAXE).harvestLevel(0).sound(SoundType.WOOD)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> POURUS_PETRIFIED_LOG		= HELPER.registerBlock("pourus_petrified_log", () -> new PourusBlock(AbstractBlock.Properties.from(PETRIFIED_LOG.get()).tickRandomly()), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> STRIPPED_PETRIFIED_LOG 	= HELPER.registerBlock("stripped_petrified_log", () -> new RotatedPillarBlock(Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(2.4f, 3.0f).harvestTool(ToolType.PICKAXE).harvestLevel(0).sound(SoundType.WOOD)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> STRIPPED_PETRIFIED_WOOD 	= HELPER.registerBlock("stripped_petrified_wood", () -> new RotatedPillarBlock(Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(2.4f, 3.0f).harvestTool(ToolType.PICKAXE).harvestLevel(0).sound(SoundType.WOOD)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> PETRIFIED_WOOD 			= HELPER.registerBlock("petrified_wood", () -> new RotatedPillarBlock(Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(2.4f, 3.0f).harvestTool(ToolType.PICKAXE).harvestLevel(0).sound(SoundType.WOOD)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> PETRIFIED_SLAB 			= HELPER.registerBlock("petrified_slab", () -> new SlabBlock(Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(2.5f, 3.0f).harvestTool(ToolType.PICKAXE).harvestLevel(0).sound(SoundType.WOOD)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> PETRIFIED_STAIRS 			= HELPER.registerBlock("petrified_stairs", () -> new StairsBlock(() -> PETRIFIED_PLANKS.get().getDefaultState(), Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(2.5f, 3.0f).harvestTool(ToolType.PICKAXE).harvestLevel(0).sound(SoundType.WOOD)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> PETRIFIED_FENCE 			= HELPER.registerBlock("petrified_fence", () -> new FenceBlock(Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(2.5f, 3.0f).harvestTool(ToolType.PICKAXE).harvestLevel(0).sound(SoundType.WOOD)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> PETRIFIED_PRESSURE_PLATE 	= HELPER.registerBlock("petrified_pressure_plate", () -> new CustomPressurePlateBlock(CustomPressurePlateBlock.Sensitivity.EVERYTHING ,Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(0.5f).harvestTool(ToolType.PICKAXE).harvestLevel(0).sound(SoundType.WOOD)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> PETRIFIED_FENCE_GATE 		= HELPER.registerBlock("petrified_fence_gate", () -> new FenceGateBlock(Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(2.5f, 3.0f).harvestTool(ToolType.PICKAXE).harvestLevel(0).sound(SoundType.WOOD)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> PETRIFIED_TRAPDOOR 		= HELPER.registerBlock("petrified_trapdoor", () -> new CustomTrapDoorBlock(Block.Properties.create(Material.ROCK).setRequiresTool().notSolid().hardnessAndResistance(2.5f, 3.0f).harvestTool(ToolType.PICKAXE).harvestLevel(0).sound(SoundType.WOOD)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> PETRIFIED_BUTTON 			= HELPER.registerBlock("petrified_button", () -> new CustomWoodButtonBlock(Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(0.5f).harvestTool(ToolType.PICKAXE).harvestLevel(0).sound(SoundType.WOOD)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> PETRIFIED_DOOR 			= HELPER.registerBlock("petrified_door", () -> new CustomDoorBlock(Block.Properties.create(Material.ROCK).setRequiresTool().notSolid().hardnessAndResistance(2.5f, 3.0f).harvestTool(ToolType.PICKAXE).harvestLevel(0).sound(SoundType.WOOD)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> SHALE			 			= HELPER.registerBlock("shale", () -> new Block(Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> SHALE_SLAB 				= HELPER.registerBlock("shale_slab", () -> new SlabBlock(Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> SHALE_STAIRS 				= HELPER.registerBlock("shale_stairs", () -> new StairsBlock(() -> SHALE.get().getDefaultState(), Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.WOOD)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> POLISHED_SHALE			= HELPER.registerBlock("polished_shale", () -> new Block(Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> POLISHED_SHALE_SLAB 		= HELPER.registerBlock("polished_shale_slab", () -> new SlabBlock(Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> POLISHED_SHALE_STAIRS 	= HELPER.registerBlock("polished_shale_stairs", () -> new StairsBlock(() -> POLISHED_SHALE.get().getDefaultState(), Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.WOOD)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> SHALE_WALL 				= HELPER.registerBlock("shale_wall", () -> new WallBlock(Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> LIMESTONE		 			= HELPER.registerBlock("limestone", () -> new Block(Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> LIMESTONE_SLAB 			= HELPER.registerBlock("limestone_slab", () -> new SlabBlock(Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> LIMESTONE_STAIRS 			= HELPER.registerBlock("limestone_stairs", () -> new StairsBlock(() -> LIMESTONE.get().getDefaultState(), Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.WOOD)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> POLISHED_LIMESTONE		= HELPER.registerBlock("polished_limestone", () -> new Block(Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> POLISHED_LIMESTONE_SLAB 	= HELPER.registerBlock("polished_limestone_slab", () -> new SlabBlock(Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> POLISHED_LIMESTONE_STAIRS = HELPER.registerBlock("polished_limestone_stairs", () -> new StairsBlock(() -> POLISHED_LIMESTONE.get().getDefaultState(), Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.WOOD)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> LIMESTONE_WALL 			= HELPER.registerBlock("limestone_wall", () -> new WallBlock(Block.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> STONE_BRICK_PILLAR		= HELPER.registerBlock("stone_brick_pillar", () -> new RotatedPillarBlock(RotatedPillarBlock.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).harvestLevel(0).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> ASH_BLOCK 				= HELPER.registerBlock("ash_block", () -> new AshFullBlock(Block.Properties.create(Material.SNOW_BLOCK, MaterialColor.BLACK).harvestTool(ToolType.SHOVEL).setRequiresTool().hardnessAndResistance(0.2f).sound(SoundType.SNOW).tickRandomly()), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> ASH						= HELPER.registerBlock("ash", () -> new AshBlock(AbstractBlock.Properties.create(Material.SNOW, MaterialColor.BLACK).harvestTool(ToolType.SHOVEL).tickRandomly().hardnessAndResistance(0.1f).setRequiresTool().sound(SoundType.SNOW)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> ARIDROCK 					= HELPER.registerBlock("aridrock", () -> new Block(Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> POLISHED_ARIDROCK 		= HELPER.registerBlock("polished_aridrock", () -> new Block(Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> ARIDROCK_GOLD_ORE 		= HELPER.registerBlock("aridrock_gold_ore", () -> new Block(Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(3.0F, 3.0F).harvestTool(ToolType.PICKAXE).harvestLevel(2).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> ARIDROCK_IRON_ORE 		= HELPER.registerBlock("aridrock_iron_ore", () -> new Block(Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(3.0F, 3.0F).harvestTool(ToolType.PICKAXE).harvestLevel(1).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> ARIDROCK_COAL_ORE 		= HELPER.registerBlock("aridrock_coal_ore", () -> new DDOreBlock(Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(3.0F, 3.0F).harvestTool(ToolType.PICKAXE).harvestLevel(0).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> ARIDROCK_LAPIS_ORE 		= HELPER.registerBlock("aridrock_lapis_ore", () -> new DDOreBlock(Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(3.0F, 3.0F).harvestTool(ToolType.PICKAXE).harvestLevel(1).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> ARIDROCK_DIAMOND_ORE 		= HELPER.registerBlock("aridrock_diamond_ore", () -> new DDOreBlock(Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(3.0F, 3.0F).harvestTool(ToolType.PICKAXE).harvestLevel(2).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> ARIDROCK_REDSTONE_ORE 	= HELPER.registerBlock("aridrock_redstone_ore", () -> new RedstoneOreBlock(Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(3.0F, 3.0F).setLightLevel(getLightValueLit(9)).harvestTool(ToolType.PICKAXE).harvestLevel(2).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> ARIDROCK_SILVER_ORE 		= HELPER.registerBlock("aridrock_silver_ore", () -> new Block(Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(3.0F, 3.0F).harvestTool(ToolType.PICKAXE).harvestLevel(2).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> LIMESTONE_GOLD_ORE 		= HELPER.registerBlock("limestone_gold_ore", () -> new Block(Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(3.0F, 3.0F).harvestTool(ToolType.PICKAXE).harvestLevel(2).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> LIMESTONE_IRON_ORE 		= HELPER.registerBlock("limestone_iron_ore", () -> new Block(Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(3.0F, 3.0F).harvestTool(ToolType.PICKAXE).harvestLevel(1).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> LIMESTONE_COAL_ORE 		= HELPER.registerBlock("limestone_coal_ore", () -> new DDOreBlock(Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(3.0F, 3.0F).harvestTool(ToolType.PICKAXE).harvestLevel(0).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> LIMESTONE_LAPIS_ORE 		= HELPER.registerBlock("limestone_lapis_ore", () -> new DDOreBlock(Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(3.0F, 3.0F).harvestTool(ToolType.PICKAXE).harvestLevel(1).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> LIMESTONE_DIAMOND_ORE 	= HELPER.registerBlock("limestone_diamond_ore", () -> new DDOreBlock(Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(3.0F, 3.0F).harvestTool(ToolType.PICKAXE).harvestLevel(2).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> LIMESTONE_REDSTONE_ORE 	= HELPER.registerBlock("limestone_redstone_ore", () -> new RedstoneOreBlock(Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(3.0F, 3.0F).setLightLevel(getLightValueLit(9)).harvestTool(ToolType.PICKAXE).harvestLevel(2).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> LIMESTONE_SILVER_ORE 		= HELPER.registerBlock("limestone_silver_ore", () -> new Block(Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(3.0F, 3.0F).harvestTool(ToolType.PICKAXE).harvestLevel(2).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> ARIDROCK_STAIRS 			= HELPER.registerBlock("aridrock_stairs", () -> new StairsBlock(() -> ARIDROCK.get().getDefaultState(), Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> ARIDROCK_SLAB				= HELPER.registerBlock("aridrock_slab", () -> new SlabBlock(Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> ARIDROCK_WALL				= HELPER.registerBlock("aridrock_wall", () -> new WallBlock(Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> POLISHED_ARIDROCK_STAIRS  = HELPER.registerBlock("polished_aridrock_stairs", () -> new StairsBlock(() -> POLISHED_ARIDROCK.get().getDefaultState(), Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> POLISHED_ARIDROCK_SLAB	= HELPER.registerBlock("polished_aridrock_slab", () -> new SlabBlock(Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.STONE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> COBBLED_SANDSTONE 		= HELPER.registerBlock("cobbled_sandstone", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(1.0F)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> LUSH_ARIDROCK 			= HELPER.registerBlock("lush_aridrock", () -> new LushAridrockBlock(Block.Properties.create(Material.ROCK, MaterialColor.LIME).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).sound(SoundType.STONE).tickRandomly()), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> GRIMESTONE				= HELPER.registerBlock("grimestone", () -> new RotatedPillarBlock(AbstractBlock.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> POLISHED_GRIMESTONE		= HELPER.registerBlock("polished_grimestone", () -> new Block(AbstractBlock.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> MOSSY_GRIMESTONE			= HELPER.registerBlock("mossy_grimestone", () -> new MossyGrimestoneBlock(AbstractBlock.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> GLOWSHROOM				= HELPER.registerBlock("glowshroom", () -> new Glowshroom(AbstractBlock.Properties.create(Material.PLANTS).hardnessAndResistance(0.0F, 1.0F).sound(SoundType.SLIME).setLightLevel(value -> 7).doesNotBlockMovement()), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> GLOWSHROOM_CAP			= HELPER.registerBlock("glowshroom_cap", GlowshroomCap::new);
	public static final RegistryObject<Block> GLOWSHROOM_STEM			= HELPER.registerBlock("glowshroom_stem", () -> new Block(AbstractBlock.Properties.create(Material.ORGANIC).hardnessAndResistance(0.2F).sound(SoundType.WOOD).sound(SoundType.HYPHAE)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> GLOWSHROOM_BLOCK			= HELPER.registerBlock("glowshroom_block", () -> new Block(AbstractBlock.Properties.create(Material.ORGANIC).setLightLevel(value -> 8).hardnessAndResistance(0.2F).sound(SoundType.SLIME)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> GLOWSPURS					= HELPER.registerBlock("glowspurs", () -> new SpurBlock(AbstractBlock.Properties.create(Material.ORGANIC).hardnessAndResistance(0.2F).sound(SoundType.SLIME).doesNotBlockMovement()), DarkerDepths.DARKER_DEPTHS);
	//public static final RegistryObject<Block> GLOWSHROOM_WALL			= HELPER.registerBlock("glowshroom_wall", () -> new WallFungusBlock(AbstractBlock.Properties.create(Material.ORGANIC).hardnessAndResistance(0.0f, 1.0f).sound(SoundType.SLIME).doesNotBlockMovement().setLightLevel(value -> 10)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> GEYSER					= HELPER.registerBlock("geyser", () -> new GeyserBlock(AbstractBlock.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F).tickRandomly()), DarkerDepths.DARKER_DEPTHS);

	//DECORATION
	public static final RegistryObject<Block> CRYSTAL_MELON 			= HELPER.registerBlock("crystal_melon", CrystalMelon::new, DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> AMETHYST_CRYSTAL 			= HELPER.registerBlock("amethyst_crystal", () -> new AbstractGemStoneBlock(14, 2, Block.Properties.create(Material.ROCK).hardnessAndResistance(1.0f, 1.0f).harvestTool(ToolType.PICKAXE).harvestLevel(2).sound(SoundType.GLASS).setLightLevel(value -> 10)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> AMETHYST_CRYSTAL_BLOCK	= HELPER.registerBlock("amethyst_crystal_block", () -> new Block(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.0f, 1.0f).harvestTool(ToolType.PICKAXE).harvestLevel(2).sound(SoundType.GLASS).setLightLevel(value -> 10)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> CELESTINE_CRYSTAL 		= HELPER.registerBlock("celestine_crystal", () -> new ClusterBlock(14, 2, AbstractBlock.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(1.0f).harvestTool(ToolType.PICKAXE).harvestLevel(2).sound(SoundType.GLASS).setLightLevel(value -> 10)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> CELESTINE_CRYSTAL_BLOCK	= HELPER.registerBlock("celestine_crystal_block", () -> new Block(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.0f, 1.0f).harvestTool(ToolType.PICKAXE).harvestLevel(2).sound(SoundType.GLASS).setLightLevel(value -> 10)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> REDSTONE_CLUSTER 			= HELPER.registerBlock("redstone_cluster", () -> new AbstractGemStoneBlock(16, 2, AbstractBlock.Properties.create(Material.ROCK).setRequiresTool().hardnessAndResistance(1.0f).harvestTool(ToolType.PICKAXE).harvestLevel(2).sound(SoundType.STONE).setLightLevel(value -> 10)));
	public static final RegistryObject<Block> REDSTONE_CLUSTER_BLOCK	= HELPER.registerBlock("redstone_cluster_block", () -> new Block(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.0f, 1.0f).harvestTool(ToolType.PICKAXE).harvestLevel(2).sound(SoundType.STONE).setLightLevel(value -> 10)));
	public static final RegistryObject<Block> AMBER 					= HELPER.registerBlock("amber", () -> new AbstractGemStoneBlock(4, 2, AbstractBlock.Properties.create(DDMaterial.AMBER).setRequiresTool().hardnessAndResistance(1.0f).harvestTool(ToolType.PICKAXE).harvestLevel(2).sound(SoundType.GLASS).setLightLevel(value -> 7)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> ROPE						= HELPER.registerBlock("rope", () -> new RopeBlock(RopeBlock.Properties.create(Material.MISCELLANEOUS).zeroHardnessAndResistance().sound(SoundType.CLOTH)));
	public static final RegistryObject<Block> ROOTS 					= HELPER.registerBlock("roots", () -> new RootsBlock(AbstractBlock.Properties.create(Material.TALL_PLANTS, MaterialColor.WOOD).doesNotBlockMovement().zeroHardnessAndResistance().sound(SoundType.PLANT)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> LONG_ROOTS 				= HELPER.registerBlock("long_roots", () -> new HangingDoublePlantBlock(AbstractBlock.Properties.create(Material.TALL_PLANTS, MaterialColor.WOOD).doesNotBlockMovement().zeroHardnessAndResistance().sound(SoundType.PLANT)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> DRY_SPROUTS 				= HELPER.registerBlock("dry_sprouts", () -> new DrySproutsBlock(AbstractBlock.Properties.from(Blocks.DEAD_BUSH)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> DETRITUS	 				= HELPER.registerBlock("detritus", () -> new DetritusBlock(AbstractBlock.Properties.from(Blocks.DEAD_BUSH)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> LUSH_SPROUTS 				= HELPER.registerBlock("lush_sprouts", () -> new SproutsBlock(AbstractBlock.Properties.from(Blocks.GRASS)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> MOSSY_SPROUTS 			= HELPER.registerBlock("mossy_sprouts", () -> new SproutsBlock(AbstractBlock.Properties.from(Blocks.GRASS)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> ALOE 						= HELPER.registerBlock("aloe", () -> new BushBlock(AbstractBlock.Properties.from(Blocks.GRASS)), DarkerDepths.DARKER_DEPTHS);
	public static final RegistryObject<Block> POTTED_GLOWSHROOM			= HELPER.registerBlock("potted_glowshroom", () -> new FlowerPotBlock(GLOWSHROOM.get(), AbstractBlock.Properties.create(Material.MISCELLANEOUS).zeroHardnessAndResistance().notSolid()));
	public static final RegistryObject<Block> POTTED_DETRITUS			= HELPER.registerBlock("potted_detritus", () -> new FlowerPotBlock(DETRITUS.get(), AbstractBlock.Properties.create(Material.MISCELLANEOUS).zeroHardnessAndResistance().notSolid()));

	//REDSTONE
	public static final RegistryObject<Block> HEART_CHAMBER				= HELPER.registerBlock("heart_chamber", () -> new HeartChamberBlock(Block.Properties.create(Material.ROCK, MaterialColor.SAND).setRequiresTool().hardnessAndResistance(1.5f, 6.0f).harvestTool(ToolType.PICKAXE).harvestLevel(1).sound(SoundType.STONE)));

	private static ToIntFunction<BlockState> getLightValueLit(int lightValue) {
		return (value) -> {
			return value.get(BlockStateProperties.LIT) ? lightValue : 0;
		};
	}
}