modLoader="javafml"
loaderVersion="[39,)"
license="All Rights Reserved"
[[mods]]
modId="darkerdepths"
version="${file.jarVersion}"
displayName="DarkerDepths"
authors="Nate, Blackgear, Toxteer, Orcinus"
description='''
A mod all about expanding vanilla caves

Author:
- Nate

Main Developers:
- Orcinus
- Blackgear

Artist:
- Nate
- Toxteer

Ambasssador:
- Qbert
'''
[[dependencies.darkerdepths]]
   modId="forge"
   mandatory=true
   versionRange="[39,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.darkerdepths]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.1,1.19)"
   ordering="NONE"
   side="BOTH"
