modLoader="javafml"

loaderVersion="[1,)"

license="Creative Commons"

[[mods]]
modId="darkerdepths"

version="${mod_version}"

displayName="Darker Depths"

authors="Naterbobber, Blackgear, Toxteer, Orcinus"

description='''
A mod to expand the underground

Author:
- Naterbobber

Main Developers:
- Naterbobber
- Orcinus
- Blackgear

Artist:
- Naterbobber
- Toxteer

-Other Contributors:
- MHImoment

'''

[[mixins]]
config="darkerdepths.mixins.json"


[[dependencies.darkerdepths]]
modId="neoforge"
mandatory=true
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.darkerdepths]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.darkerdepths]]
modId="geckolib"
mandatory=true
versionRange="[4.5,)"
ordering="NONE"
side="BOTH"
