modLoader="javafml"
loaderVersion="[39,)"
license="All Rights Reserved"
[[mods]]
modId="darkerdepths"
version="${file.jarVersion}"
displayName="Darker Depths"
authors="Nate, Blackgear, Toxteer, Orcinus"
description='''
A mod to expand the underground

Author:
- Nate

Main Developers:
- Nate
- Orcinus
- Blackgear

Artist:
- Nate
- Toxteer

'''
[[dependencies.darkerdepths]]
   modId="forge"
   mandatory=true
   versionRange="[39,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.darkerdepths]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1]"
   ordering="NONE"
   side="BOTH"

[[dependencies.darkerdepths]]
modId="geckolib"
mandatory=true
versionRange="[4.7,)"
ordering="NONE"
side="BOTH"
