modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="darkerdepths"

version="${mod_version}"

displayName="Darker Depths"

authors="Naterbobber, Blackgear, Toxteer, Orcinus"

description='''
A mod to expand the underground

Author:
- Naterbobber

Main Developers:
- Naterbobber
- Orcinus
- Blackgear

Artist:
- Naterbobber
- Toxteer

-Other Contributors:
- MHImoment

'''

[[mixins]]
    config="darkerdepths.mixins.json"

[[dependencies.darkerdepths]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.darkerdepths]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.darkerdepths]]
    modId="geckolib"
    type="required"
    versionRange="${geckolib_version}"
    ordering="NONE"
    side="BOTH"
