package com.naterbobber.darkerdepths.data.loot;

import com.naterbobber.darkerdepths.block.custom.AshBlock;
import com.naterbobber.darkerdepths.block.custom.GlowshroomBlock;
import com.naterbobber.darkerdepths.block.generic.VerticalSlabBlock;
import com.naterbobber.darkerdepths.init.DDBlocks;
import com.naterbobber.darkerdepths.init.DDItems;
import net.minecraft.advancements.critereon.StatePropertiesPredicate;
import net.minecraft.core.Holder;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.loot.BlockLootSubProvider;
import net.minecraft.world.flag.FeatureFlags;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.state.properties.IntegerProperty;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.functions.SetItemCountFunction;
import net.minecraft.world.level.storage.loot.predicates.LootItemBlockStatePropertyCondition;
import net.minecraft.world.level.storage.loot.predicates.LootItemRandomChanceCondition;
import net.minecraft.world.level.storage.loot.providers.number.ConstantValue;
import net.minecraft.world.level.storage.loot.providers.number.NumberProvider;
import net.minecraft.world.level.storage.loot.providers.number.UniformGenerator;

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.function.Function;
import java.util.stream.Collectors;

public class DDBlockLoot extends BlockLootSubProvider {

    private final Set<Block> blockIgnores = new HashSet<>();

    protected DDBlockLoot(HolderLookup.Provider registries) {
        super(Set.of(), FeatureFlags.REGISTRY.allFlags(), registries);
    }

    @Override
    protected void generate() {
        add(DDBlocks.PETRIFIED_WALL_SIGN.get(), block -> createSingleItemTable(DDItems.PETRIFIED_SIGN.get()));
        add(DDBlocks.PETRIFIED_WALL_HANGING_SIGN.get(), block -> createSingleItemTable(DDItems.PETRIFIED_HANGING_SIGN.get()));
        skipBlock(DDBlocks.MOB_PLACER.get());
        add(DDBlocks.MOSSY_GRIMESTONE.get(), block -> createSingleItemTableWithSilkTouch(DDBlocks.MOSSY_GRIMESTONE.get(), DDBlocks.GRIMESTONE.asItem()));
        add(DDBlocks.ARID_DEEPSLATE.get(), block -> createSingleItemTableWithSilkTouch(DDBlocks.ARID_DEEPSLATE.get(), Blocks.DEEPSLATE.asItem()));
        add(DDBlocks.AMBER_CLUSTER.get(), block -> createSingleItemTableWithSilkTouch(DDBlocks.AMBER_CLUSTER.get(), DDItems.AMBER.get()));
        add(DDBlocks.GLIMMERING_VINES.get(), block -> createShearsOrChanceBreakLoot(DDBlocks.GLIMMERING_VINES.get(), DDItems.GLOW_GRIME.get(), 0.3F));
        add(DDBlocks.GLIMMERING_VINE_PLANT.get(), block -> createShearsOrChanceBreakLoot(DDBlocks.GLIMMERING_VINES.get(), DDItems.GLOW_GRIME.get(), 0.3F));
        add(DDBlocks.GLOWSHROOM.get(), block -> createStageBasedLoot(DDBlocks.GLOWSHROOM.get(), GlowshroomBlock.GLOWSHROOM_CLUSTERS));
        add(DDBlocks.ASH.get(), block -> createStageBasedLoot(DDBlocks.ASH.get(), AshBlock.LAYERS));
        add(DDBlocks.POROUS_PETRIFIED_LOG.get(), block -> createSingleItemTableWithSilkTouch(DDBlocks.POROUS_PETRIFIED_LOG.get(), DDItems.AMBER.get(), UniformGenerator.between(2F, 5F)));
        add(DDBlocks.PETRIFIED_BOOKSHELF.get(), block -> createSingleItemTableWithSilkTouch(DDBlocks.PETRIFIED_BOOKSHELF.get(), Items.BOOK, ConstantValue.exactly(3.0F)));

        autoGenerateDrops();
    }

    @Override
    protected Iterable<Block> getKnownBlocks() {
        return DDBlocks.BLOCKS.getEntries().stream().map(Holder::value)::iterator;
    }

    private void skipBlock(Block block) {
        blockIgnores.add(block);
    }

    @Override
    protected void add(Block block, LootTable.Builder builder) {
        super.add(block, builder);
        blockIgnores.add(block);
    }

    @Override
    protected void add(Block block, Function<Block, LootTable.Builder> factory) {
        super.add(block, factory);
        blockIgnores.add(block);
    }

    private void autoGenerateDrops() {
        Set<Block> defaultDropBlocks = DDBlocks.BLOCKS
                .getEntries()
                .stream()
                .map(Holder::value)
                .filter(item -> !blockIgnores.contains(item)).collect(Collectors.toSet());

        defaultDropBlocks.forEach(block -> {
            switch (block) {
                case SlabBlock b -> add (b, createSlabItemTable(b));
                case VerticalSlabBlock b -> add(b, createSlabItemTable(b));
                case DoorBlock b -> add(b, createDoorTable(b));
                case BushBlock b -> add(b, createGrassDrops(b));
                case FlowerPotBlock b -> add(b, createPotFlowerItemTable(b.getPotted()));
                default -> dropSelf(block);
            }
        });
    }

    /**
     * @param block Block which drops itself.
     * @param stageProperty Stage property that increases when placing more in the same block.
     * @return Loot table which drops an item that for every increase of stage, it will drop itself again.
     */
    private LootTable.Builder createStageBasedLoot(Block block, IntegerProperty stageProperty) {
        List<Integer> stages = stageProperty.getPossibleValues()
                .stream()
                .filter(item -> item >= 2)
                .toList();

        return LootTable.lootTable()
                .withPool(
                        LootPool.lootPool()
                                .setRolls(ConstantValue.exactly(1.0F))
                                .add(
                                        this.applyExplosionDecay(
                                                block,
                                                LootItem.lootTableItem(block)
                                                        .apply(
                                                                stages,
                                                                stage -> SetItemCountFunction.setCount(ConstantValue.exactly((float)stage))
                                                                        .when(
                                                                                LootItemBlockStatePropertyCondition.hasBlockStateProperties(block)
                                                                                        .setProperties(
                                                                                                StatePropertiesPredicate.Builder.properties()
                                                                                                        .hasProperty(stageProperty, stage)
                                                                                        )
                                                                        )
                                                        )
                                        )
                                )
                );
    }

    /**
     * @param block Block which drops 100% of the time from shears.
     * @param item Item dropped at dropChance from the block without using shears.
     * @return Loot table which drops an item with a chance when broken without shears, and drops itself when broken with shears.
     */
    private LootTable.Builder createShearsOrChanceBreakLoot(Block block, Item item, float dropChance) {
        return LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(ConstantValue.exactly(1.0F))
                        .add(LootItem.lootTableItem(block)
                                .when(HAS_SHEARS)
                        )
                )
                .withPool(LootPool.lootPool()
                        .setRolls(ConstantValue.exactly(1.0F))
                        .add(LootItem.lootTableItem(item)
                                .when(HAS_SHEARS.invert())
                                .when(LootItemRandomChanceCondition.randomChance(dropChance))
                        )
                        .when(HAS_SHEARS.invert())
                );
    }
}
