package com.naterbobber.darkerdepths.data.loot;

import com.naterbobber.darkerdepths.blocks.GlowshroomBlock;
import com.naterbobber.darkerdepths.blocks.VerticalSlabBlock;
import com.naterbobber.darkerdepths.init.DDBlocks;
import com.naterbobber.darkerdepths.init.DDItems;
import net.minecraft.advancements.critereon.StatePropertiesPredicate;
import net.minecraft.core.Holder;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.loot.BlockLootSubProvider;
import net.minecraft.data.loot.packs.VanillaBlockLoot;
import net.minecraft.world.flag.FeatureFlagSet;
import net.minecraft.world.flag.FeatureFlags;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.state.properties.IntegerProperty;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.functions.LootItemFunction;
import net.minecraft.world.level.storage.loot.functions.SetItemCountFunction;
import net.minecraft.world.level.storage.loot.predicates.LootItemBlockStatePropertyCondition;
import net.minecraft.world.level.storage.loot.predicates.LootItemRandomChanceCondition;
import net.minecraft.world.level.storage.loot.providers.number.ConstantValue;
import net.minecraft.world.level.storage.loot.providers.number.NumberProvider;
import net.neoforged.neoforge.registries.DeferredHolder;

import java.util.HashSet;
import java.util.Set;
import java.util.function.Function;
import java.util.stream.Collectors;

public class DDBlockLoot extends BlockLootSubProvider {

    private final Set<Block> blockIgnores = new HashSet<>();


    protected DDBlockLoot(HolderLookup.Provider registries) {
        super(Set.of(), FeatureFlags.REGISTRY.allFlags(), registries);
    }

    @Override
    protected void generate() {
        add(DDBlocks.PETRIFIED_SIGN.get(), block -> createSingleItemTable(DDItems.PETRIFIED_SIGN.get()));
        add(DDBlocks.PETRIFIED_WALL_SIGN.get(), block -> createSingleItemTable(DDItems.PETRIFIED_SIGN.get()));
        add(DDBlocks.PETRIFIED_HANGING_SIGN.get(), block -> createSingleItemTable(DDItems.PETRIFIED_HANGING_SIGN.get()));
        add(DDBlocks.PETRIFIED_WALL_HANGING_SIGN.get(), block -> createSingleItemTable(DDItems.PETRIFIED_HANGING_SIGN.get()));
        add(DDBlocks.POTTED_GLOWSHROOM.get(), block -> createPotFlowerItemTable(DDBlocks.GLOWSHROOM.get()));
        skipBlock(DDBlocks.MOB_PLACER.get());
        add(DDBlocks.DRY_SPROUTS.get(), block -> createGrassDrops(DDBlocks.DRY_SPROUTS.get()));
        add(DDBlocks.MOSSY_SPROUTS.get(), block -> createGrassDrops(DDBlocks.MOSSY_SPROUTS.get()));
        add(DDBlocks.MOSSY_GRIMESTONE.get(), block -> createSingleItemTableWithSilkTouch(DDBlocks.MOSSY_GRIMESTONE.get(), DDBlocks.GRIMESTONE.asItem()));
        add(DDBlocks.ARID_DEEPSLATE.get(), block -> createSingleItemTableWithSilkTouch(DDBlocks.ARID_DEEPSLATE.get(), Blocks.DEEPSLATE.asItem()));
        add(DDBlocks.AMBER_CLUSTER.get(), block -> createSingleItemTableWithSilkTouch(DDBlocks.AMBER_CLUSTER.get(), DDItems.AMBER.get()));
        add(DDBlocks.GLIMMERING_VINES.get(), block -> createGlimmeringVinesLoot(DDBlocks.GLIMMERING_VINES.get(), DDItems.GLOW_GRIME.get()));
        add(DDBlocks.GLIMMERING_VINE_PLANT.get(), block -> createGlimmeringVinesLoot(DDBlocks.GLIMMERING_VINES.get(), DDItems.GLOW_GRIME.get()));

        //TODO
        //ash layers
        //glowshroom stages



        autoGenerateDrops();
    }

    @Override
    protected Iterable<Block> getKnownBlocks() {
        return DDBlocks.BLOCKS.getEntries().stream().map(Holder::value)::iterator;
    }

    private void skipBlock(Block block) {
        blockIgnores.add(block);
    }

    @Override
    protected void add(Block block, LootTable.Builder builder) {
        super.add(block, builder);
        blockIgnores.add(block);
    }

    @Override
    protected void add(Block block, Function<Block, LootTable.Builder> factory) {
        super.add(block, factory);
        blockIgnores.add(block);
    }

    private void autoGenerateDrops() {
        Set<Block> defaultDropBlocks = DDBlocks.BLOCKS
                .getEntries()
                .stream()
                .map(Holder::value)
                .filter(item -> !blockIgnores.contains(item)).collect(Collectors.toSet());

        defaultDropBlocks.forEach(block -> {
            switch (block) {
                case SlabBlock b -> add(b, createSlabItemTable(b));
                case VerticalSlabBlock b -> add(b, createSlabItemTable(b));
                case DoorBlock b -> add(b, createDoorTable(b));
                default -> dropSelf(block);
            }
        });
    }

    //finish this later
    private LootTable.Builder createCountBasedLoot(Block block, IntegerProperty countProperty, int maxAmount) {
        return new LootTable.Builder();
    }

    private LootTable.Builder createGlimmeringVinesLoot(Block block, Item item) {
        return LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(ConstantValue.exactly(1.0F))
                        .add(LootItem.lootTableItem(block)
                                .when(HAS_SHEARS)
                        )
                )
                .withPool(LootPool.lootPool()
                        .setRolls(ConstantValue.exactly(1.0F))
                        .add(LootItem.lootTableItem(item)
                                .when(HAS_SHEARS.invert())
                                .when(LootItemRandomChanceCondition.randomChance(0.3F))
                        )
                        .when(HAS_SHEARS.invert())
                );
    }
}
