package com.naterbobber.darkerdepths.init;

import com.google.common.collect.Maps;
import com.naterbobber.darkerdepths.DarkerDepths;
import com.naterbobber.darkerdepths.blocks.*;
import net.minecraft.core.particles.ParticleOptions;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.AmethystClusterBlock;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.ButtonBlock;
import net.minecraft.world.level.block.DoorBlock;
import net.minecraft.world.level.block.DropExperienceBlock;
import net.minecraft.world.level.block.FenceBlock;
import net.minecraft.world.level.block.FenceGateBlock;
import net.minecraft.world.level.block.FlowerPotBlock;
import net.minecraft.world.level.block.LanternBlock;
import net.minecraft.world.level.block.PressurePlateBlock;
import net.minecraft.world.level.block.RedStoneOreBlock;
import net.minecraft.world.level.block.RedstoneLampBlock;
import net.minecraft.world.level.block.RotatedPillarBlock;
import net.minecraft.world.level.block.SlabBlock;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.StairBlock;
import net.minecraft.world.level.block.TrapDoorBlock;
import net.minecraft.world.level.block.WallBlock;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.MapColor;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import net.minecraft.core.particles.ParticleTypes;

import java.util.Map;
import java.util.function.Supplier;

@Mod.EventBusSubscriber(modid = DarkerDepths.MODID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class DDBlocks {
    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, DarkerDepths.MODID);
    public static final Map<RegistryObject<? extends Item>, String> COMPAT = Maps.newLinkedHashMap();

    public static final RegistryObject<Block> PETRIFIED_PLANKS = registerBlock("petrified_planks", () -> new Block(Block.Properties.of().requiresCorrectToolForDrops().strength(2.5f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> VERTICAL_PETRIFIED_PLANKS = registerCompatBlock("quark", "vertical_petrified_planks", () -> new Block(Block.Properties.copy(PETRIFIED_PLANKS.get())));
    public static final RegistryObject<Block> PETRIFIED_LOG = registerBlock("petrified_log", () -> new RotatedPillarBlock(Block.Properties.of().requiresCorrectToolForDrops().strength(2.4f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> STRIPPED_PETRIFIED_LOG = registerBlock("stripped_petrified_log", () -> new RotatedPillarBlock(Block.Properties.of().requiresCorrectToolForDrops().strength(2.4f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> STRIPPED_PETRIFIED_WOOD = registerBlock("stripped_petrified_wood", () -> new RotatedPillarBlock(Block.Properties.of().requiresCorrectToolForDrops().strength(2.4f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PETRIFIED_WOOD = registerBlock("petrified_wood", () -> new RotatedPillarBlock(Block.Properties.of().requiresCorrectToolForDrops().strength(2.4f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PETRIFIED_SLAB = registerBlock("petrified_slab", () -> new SlabBlock(Block.Properties.of().requiresCorrectToolForDrops().strength(2.5f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PETRIFIED_VERTICAL_SLAB = registerCompatBlock("quark", "petrified_vertical_slab", () -> new VerticalSlabBlock(BlockBehaviour.Properties.copy(PETRIFIED_SLAB.get())));
    public static final RegistryObject<Block> PETRIFIED_STAIRS = registerBlock("petrified_stairs", () -> new StairBlock(() -> PETRIFIED_PLANKS.get().defaultBlockState(), Block.Properties.of().requiresCorrectToolForDrops().strength(2.5f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> POROUS_PETRIFIED_LOG = registerBlock("porous_petrified_log", () -> new PorousBlock(BlockBehaviour.Properties.copy(PETRIFIED_LOG.get()).randomTicks().lightLevel(value -> 6)));
    public static final RegistryObject<Block> MOSSY_GRIMESTONE = registerBlock("mossy_grimestone", () -> new MossyGrimestoneBlock(BlockBehaviour.Properties.of().strength(1.5F, 6.0F).requiresCorrectToolForDrops().randomTicks().sound(DDSoundEvents.GRIMESTONE)));
    public static final RegistryObject<Block> SHALE = registerBlock("shale", () -> new Block(Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> SHALE_SLAB = registerBlock("shale_slab", () -> new SlabBlock(Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> SHALE_VERTICAL_SLAB = registerCompatBlock("quark", "shale_vertical_slab", () -> new VerticalSlabBlock(BlockBehaviour.Properties.copy(SHALE_SLAB.get())));
    public static final RegistryObject<Block> SHALE_STAIRS = registerBlock("shale_stairs", () -> new StairBlock(() -> SHALE.get().defaultBlockState(), Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> POLISHED_SHALE = registerBlock("polished_shale", () -> new Block(Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> POLISHED_SHALE_SLAB = registerBlock("polished_shale_slab", () -> new SlabBlock(Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> POLISHED_SHALE_VERTICAL_SLAB = registerCompatBlock("quark", "polished_shale_vertical_slab", () -> new VerticalSlabBlock(BlockBehaviour.Properties.copy(POLISHED_SHALE_SLAB.get())));
    public static final RegistryObject<Block> POLISHED_SHALE_STAIRS = registerBlock("polished_shale_stairs", () -> new StairBlock(() -> POLISHED_SHALE.get().defaultBlockState(), Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> SHALE_BRICKS = registerBlock("shale_bricks", () -> new Block(Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> SHALE_BRICKS_SLAB = registerBlock("shale_bricks_slab", () -> new SlabBlock(Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> SHALE_BRICKS_VERTICAL_SLAB = registerCompatBlock("quark", "shale_bricks_vertical_slab", () -> new VerticalSlabBlock(Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> SHALE_BRICKS_STAIRS = registerBlock("shale_bricks_stairs", () -> new StairBlock(SHALE_BRICKS.get().defaultBlockState(), Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> CHISELED_SHALE_BRICKS = registerBlock("chiseled_shale_bricks", () -> new Block(Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> CRACKED_SHALE_BRICKS = registerBlock("cracked_shale_bricks", () -> new Block(Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> ARIDROCK = registerBlock("aridrock", () -> new RotatedPillarBlock(Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> ARIDROCK_SLAB = registerBlock("aridrock_slab", () -> new SlabBlock(Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> ARIDROCK_VERTICAL_SLAB = registerCompatBlock("quark", "aridrock_vertical_slab", () -> new VerticalSlabBlock(Block.Properties.copy(ARIDROCK_SLAB.get())));
    public static final RegistryObject<Block> ARIDROCK_STAIRS = registerBlock("aridrock_stairs", () -> new StairBlock(() -> ARIDROCK.get().defaultBlockState(), Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> POLISHED_ARIDROCK = registerBlock("polished_aridrock", () -> new Block(Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> POLISHED_ARIDROCK_SLAB = registerBlock("polished_aridrock_slab", () -> new SlabBlock(Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> POLISHED_ARIDROCK_VERTICAL_SLAB = registerCompatBlock("quark", "polished_aridrock_vertical_slab", () -> new VerticalSlabBlock(Block.Properties.copy(POLISHED_ARIDROCK_SLAB.get())));
    public static final RegistryObject<Block> POLISHED_ARIDROCK_STAIRS = registerBlock("polished_aridrock_stairs", () -> new StairBlock(() -> POLISHED_ARIDROCK.get().defaultBlockState(), Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> ARIDROCK_BRICKS = registerBlock("aridrock_bricks", () -> new Block(BlockBehaviour.Properties.of().sound(SoundType.STONE).strength(1.5F, 6.0F).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> ARIDROCK_BRICKS_SLAB = registerBlock("aridrock_bricks_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().sound(SoundType.STONE).strength(1.5F, 6.0F).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> ARIDROCK_BRICKS_VERTICAL_SLAB = registerCompatBlock("quark", "aridrock_bricks_vertical_slab", () -> new VerticalSlabBlock(BlockBehaviour.Properties.copy(ARIDROCK_BRICKS_SLAB.get())));
    public static final RegistryObject<Block> ARIDROCK_BRICKS_STAIRS = registerBlock("aridrock_bricks_stairs", () -> new StairBlock(ARIDROCK_BRICKS.get().defaultBlockState(), BlockBehaviour.Properties.of().sound(SoundType.STONE).strength(1.5F, 6.0F).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> CHISELED_ARIDROCK_BRICKS = registerBlock("chiseled_aridrock_bricks", () -> new Block(Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> CRACKED_ARIDROCK_BRICKS = registerBlock("cracked_aridrock_bricks", () -> new Block(BlockBehaviour.Properties.of().sound(SoundType.STONE).strength(1.5F, 6.0F).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> SKULL_WALL = registerBlock("skull_wall", () -> new Block(BlockBehaviour.Properties.of().sound(SoundType.STONE).strength(1.5F, 6.0F).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> LIMESTONE = registerBlock("limestone", () -> new LimestoneBlock(Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> LIMESTONE_SLAB = registerBlock("limestone_slab", () -> new SlabBlock(Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> LIMESTONE_VERTICAL_SLAB = registerCompatBlock("quark", "limestone_vertical_slab", () -> new VerticalSlabBlock(BlockBehaviour.Properties.copy(LIMESTONE_SLAB.get())));
    public static final RegistryObject<Block> LIMESTONE_STAIRS = registerBlock("limestone_stairs", () -> new StairBlock(() -> LIMESTONE.get().defaultBlockState(), Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> POLISHED_LIMESTONE = registerBlock("polished_limestone", () -> new Block(Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> POLISHED_LIMESTONE_SLAB = registerBlock("polished_limestone_slab", () -> new SlabBlock(Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> POLISHED_LIMESTONE_VERTICAL_SLAB = registerCompatBlock("quark", "polished_limestone_vertical_slab", () -> new VerticalSlabBlock(BlockBehaviour.Properties.copy(POLISHED_LIMESTONE_SLAB.get())));
    public static final RegistryObject<Block> POLISHED_LIMESTONE_STAIRS = registerBlock("polished_limestone_stairs", () -> new StairBlock(() -> POLISHED_LIMESTONE.get().defaultBlockState(), Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> LIMESTONE_BRICKS = registerBlock("limestone_bricks", () -> new Block(Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> LIMESTONE_BRICKS_SLAB = registerBlock("limestone_bricks_slab", () -> new SlabBlock(Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> LIMESTONE_BRICKS_VERTICAL_SLAB = registerCompatBlock("quark", "limestone_bricks_vertical_slab", () -> new VerticalSlabBlock(BlockBehaviour.Properties.copy(ARIDROCK_BRICKS_SLAB.get())));
    public static final RegistryObject<Block> LIMESTONE_BRICKS_STAIRS = registerBlock("limestone_bricks_stairs", () -> new StairBlock(() -> POLISHED_LIMESTONE.get().defaultBlockState(), Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> CHISELED_LIMESTONE_BRICKS = registerBlock("chiseled_limestone_bricks", () -> new Block(Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> CRACKED_LIMESTONE_BRICKS = registerBlock("cracked_limestone_bricks", () -> new Block(BlockBehaviour.Properties.of().sound(SoundType.STONE).strength(1.5F, 6.0F).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> ARIDROCK_GOLD_ORE = registerBlock("aridrock_gold_ore", () -> new Block(Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(3.0F, 3.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> ARIDROCK_IRON_ORE = registerBlock("aridrock_iron_ore", () -> new Block(Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(3.0F, 3.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> ARIDROCK_COAL_ORE = registerBlock("aridrock_coal_ore", () -> new DropExperienceBlock(Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(3.0F, 3.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> ARIDROCK_LAPIS_ORE = registerBlock("aridrock_lapis_ore", () -> new DropExperienceBlock(Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(3.0F, 3.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> ARIDROCK_DIAMOND_ORE = registerBlock("aridrock_diamond_ore", () -> new DropExperienceBlock(Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(3.0F, 3.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> ARIDROCK_REDSTONE_ORE = registerBlock("aridrock_redstone_ore", () -> new RedStoneOreBlock(Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(3.0F, 3.0F).lightLevel(state -> 9).sound(SoundType.STONE)));
    public static final RegistryObject<Block> ARIDROCK_SILVER_ORE = registerBlock("aridrock_silver_ore", () -> new Block(Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(3.0F, 3.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> LIMESTONE_GOLD_ORE = registerBlock("limestone_gold_ore", () -> new Block(Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(3.0F, 3.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> LIMESTONE_IRON_ORE = registerBlock("limestone_iron_ore", () -> new Block(Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(3.0F, 3.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> LIMESTONE_COAL_ORE = registerBlock("limestone_coal_ore", () -> new DropExperienceBlock(Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(3.0F, 3.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> LIMESTONE_LAPIS_ORE = registerBlock("limestone_lapis_ore", () -> new DropExperienceBlock(Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(3.0F, 3.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> LIMESTONE_DIAMOND_ORE = registerBlock("limestone_diamond_ore", () -> new DropExperienceBlock(Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(3.0F, 3.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> LIMESTONE_REDSTONE_ORE = registerBlock("limestone_redstone_ore", () -> new RedStoneOreBlock(Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(3.0F, 3.0F).lightLevel(state -> 9).sound(SoundType.STONE)));
    public static final RegistryObject<Block> LIMESTONE_SILVER_ORE = registerBlock("limestone_silver_ore", () -> new Block(Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(3.0F, 3.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> GRIMESTONE = registerBlock("grimestone", () -> new GrimestoneBlock(BlockBehaviour.Properties.of().strength(1.5F, 6.0F).sound(DDSoundEvents.GRIMESTONE).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> GRIMESTONE_SLAB = registerBlock("grimestone_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().strength(1.5F, 6.0F).sound(DDSoundEvents.GRIMESTONE).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> GRIMESTONE_VERTICAL_SLAB = registerCompatBlock("quark", "grimestone_vertical_slab", () -> new VerticalSlabBlock(BlockBehaviour.Properties.copy(GRIMESTONE_SLAB.get())));
    public static final RegistryObject<Block> GRIMESTONE_STAIRS = registerBlock("grimestone_stairs", () -> new StairBlock(GRIMESTONE.get().defaultBlockState(), BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(1.5F, 6.0F).sound(DDSoundEvents.GRIMESTONE)));
    public static final RegistryObject<Block> POLISHED_GRIMESTONE = registerBlock("polished_grimestone", () -> new Block(BlockBehaviour.Properties.of().strength(1.5F, 6.0F)));
    public static final RegistryObject<Block> POLISHED_GRIMESTONE_SLAB = registerBlock("polished_grimestone_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().strength(1.5F, 6.0F)));
    public static final RegistryObject<Block> POLISHED_GRIMESTONE_VERTICAL_SLAB = registerCompatBlock("quark", "polished_grimestone_vertical_slab", () -> new VerticalSlabBlock(Block.Properties.copy(POLISHED_GRIMESTONE_SLAB.get())));
    public static final RegistryObject<Block> POLISHED_GRIMESTONE_STAIRS = registerBlock("polished_grimestone_stairs", () -> new StairBlock(POLISHED_GRIMESTONE.get().defaultBlockState(), BlockBehaviour.Properties.of().strength(1.5F, 6.0F)));
    public static final RegistryObject<Block> CHISELED_GRIMESTONE_BRICKS = registerBlock("chiseled_grimestone_bricks", () -> new Block(BlockBehaviour.Properties.of().sound(SoundType.STONE).strength(1.5F, 6.0F).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> GRIMESTONE_BRICKS = registerBlock("grimestone_bricks", () -> new Block(BlockBehaviour.Properties.of().sound(SoundType.STONE).strength(1.5F, 6.0F).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> GRIMESTONE_BRICKS_SLAB = registerBlock("grimestone_bricks_slab", () -> new SlabBlock(BlockBehaviour.Properties.of().sound(SoundType.STONE).strength(1.5F, 6.0F).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> GRIMESTONE_BRICKS_VERTICAL_SLAB = registerCompatBlock("quark", "grimestone_bricks_vertical_slab", () -> new VerticalSlabBlock(BlockBehaviour.Properties.copy(GRIMESTONE_BRICKS_SLAB.get())));
    public static final RegistryObject<Block> GRIMESTONE_BRICKS_STAIRS = registerBlock("grimestone_bricks_stairs", () -> new StairBlock(GRIMESTONE_BRICKS.get().defaultBlockState(), BlockBehaviour.Properties.of().sound(SoundType.STONE).strength(1.5F, 6.0F).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> CRACKED_GRIMESTONE_BRICKS = registerBlock("cracked_grimestone_bricks", () -> new Block(BlockBehaviour.Properties.of().sound(SoundType.STONE).strength(1.5F, 6.0F).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> STONE_BRICK_PILLAR = registerBlock("stone_brick_pillar", () -> new RotatedPillarBlock(RotatedPillarBlock.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> ASH_BLOCK = registerBlock("ash_block", () -> new AshFullBlock(Block.Properties.of().mapColor(MapColor.COLOR_BLACK).requiresCorrectToolForDrops().strength(0.2f).sound(SoundType.SNOW).randomTicks()));
    public static final RegistryObject<Block> SILVER_ORE = registerBlock("silver_ore", () -> new Block(Block.Properties.of().requiresCorrectToolForDrops().strength(3.0F, 3.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> GLOWSHROOM = registerBlock("glowshroom", () -> new GlowshroomBlock(BlockBehaviour.Properties.of().strength(0.0F, 1.0F).sound(SoundType.SLIME_BLOCK).lightLevel((state) -> 2 + (3 * state.getValue(GlowshroomBlock.CLUSTERS_1_3))).noCollission()));
    public static final RegistryObject<Block> VOID_SOUL_TORCH = registerNoTabBlock("void_soul_torch", () -> new VoidSoulTorchBlock(BlockBehaviour.Properties.of().strength(0.0F, 1.0F).noCollission().sound(SoundType.WOOD).lightLevel(state -> 12), DDParticleTypes.VOID_SOUL_FLAME::get));
    public static final RegistryObject<Block> WALL_VOID_SOUL_TORCH = registerNoTabBlock("wall_void_soul_torch", () -> new WallVoidSoulTorchBlock(BlockBehaviour.Properties.of().strength(0.0F, 1.0F).noCollission().sound(SoundType.WOOD).lootFrom(VOID_SOUL_TORCH).lightLevel(state -> 12), DDParticleTypes.VOID_SOUL_FLAME::get));
    public static final RegistryObject<Block> GLOWSPURS = registerBlock("glowspurs", () -> new GlowspursBlock(BlockBehaviour.Properties.of().instabreak().sound(SoundType.SLIME_BLOCK).noCollission()));
    public static final RegistryObject<Block> PETRIFIED_ROOTS = registerBlock("petrified_roots", () -> new PetrifiedRootBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).offsetType(BlockBehaviour.OffsetType.XZ).noCollission().instabreak().sound(SoundType.GRASS)));
    public static final RegistryObject<Block> PETRIFIED_ROOTS_PLANT = registerNoTabBlock("petrified_roots_plant", () -> new PetrifiedRootPlantBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).offsetType(BlockBehaviour.OffsetType.XZ).noCollission().instabreak().sound(SoundType.GRASS)));
    public static final RegistryObject<Block> DRY_SPROUTS = registerBlock("dry_sprouts", () -> new DrySproutsBlock(BlockBehaviour.Properties.copy(Blocks.DEAD_BUSH).offsetType(BlockBehaviour.OffsetType.XZ)));
    public static final RegistryObject<Block> LUSH_SPROUTS = registerBlock("lush_sprouts", () -> new SproutsBlock(BlockBehaviour.Properties.copy(Blocks.GRASS).offsetType(BlockBehaviour.OffsetType.XZ)));
    public static final RegistryObject<Block> MOSSY_SPROUTS = registerBlock("mossy_sprouts", () -> new SproutsBlock(BlockBehaviour.Properties.copy(Blocks.GRASS).offsetType(BlockBehaviour.OffsetType.XZ)));
    public static final RegistryObject<Block> POTTED_GLOWSHROOM = registerNoTabBlock("potted_glowshroom", () -> new FlowerPotBlock(GLOWSHROOM.get(), BlockBehaviour.Properties.of().instabreak().noOcclusion()));
    public static final RegistryObject<Block> GLOWSPIRE = registerBlock("glowspire", () -> new GlowSpireBlock(BlockBehaviour.Properties.of().noCollission().lightLevel(value -> 8).sound(SoundType.GRASS)));
    public static final RegistryObject<Block> GLOWSPIRE_PLANT = registerNoTabBlock("glowspire_plant", () -> new GlowSpirePlantBlock(BlockBehaviour.Properties.copy(GLOWSPIRE.get()).sound(SoundType.GRASS)));
    public static final RegistryObject<Block> ASH = registerBlock("ash", () -> new AshBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).randomTicks().strength(0.1f).requiresCorrectToolForDrops().sound(SoundType.SNOW)));
    public static final RegistryObject<Block> PETRIFIED_FENCE = registerBlock("petrified_fence", () -> new FenceBlock(Block.Properties.of().requiresCorrectToolForDrops().strength(2.5f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PETRIFIED_POST = registerCompatBlock("quark", "petrified_post", () -> new WoodPostBlock(Block.Properties.of().requiresCorrectToolForDrops().noOcclusion().strength(2.5f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> STRIPPED_PETRIFIED_POST = registerCompatBlock("quark", "stripped_petrified_post", () -> new WoodPostBlock(Block.Properties.of().requiresCorrectToolForDrops().noOcclusion().strength(2.5f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> GLOWSHROOM_BLOCK = registerBlock("glowshroom_block", () -> new Block(BlockBehaviour.Properties.of().strength(0.2F).sound(SoundType.SLIME_BLOCK)));
    public static final RegistryObject<Block> GLOWSHROOM_STEM = registerBlock("glowshroom_stem", () -> new Block(BlockBehaviour.Properties.of().strength(0.2F).sound(SoundType.STEM)));
    public static final RegistryObject<Block> ROPE = registerNoTabBlock("rope", () -> new RopeBlock(BlockBehaviour.Properties.of().strength(0.1F).sound(SoundType.WOOL)));
    public static final RegistryObject<Block> SHALE_WALL = registerBlock("shale_wall", () -> new WallBlock(Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> SHALE_BRICKS_WALL = registerBlock("shale_bricks_wall", () -> new WallBlock(Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> ARIDROCK_WALL = registerBlock("aridrock_wall", () -> new WallBlock(Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> ARIDROCK_BRICKS_WALL = registerBlock("aridrock_bricks_wall", () -> new WallBlock(Block.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> LIMESTONE_WALL = registerBlock("limestone_wall", () -> new WallBlock(Block.Properties.of().requiresCorrectToolForDrops().strength(1.5f, 6.0f).sound(SoundType.STONE)));
    public static final RegistryObject<Block> LIMESTONE_BRICKS_WALL = registerBlock("limestone_bricks_wall", () -> new WallBlock(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(1.5F, 6.0F).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final RegistryObject<Block> GRIMESTONE_WALL = registerBlock("grimestone_wall", () -> new WallBlock(BlockBehaviour.Properties.of().sound(DDSoundEvents.GRIMESTONE).strength(1.5F, 6.0F).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> GRIMESTONE_BRICKS_WALL = registerBlock("grimestone_bricks_wall", () -> new WallBlock(BlockBehaviour.Properties.of().sound(SoundType.STONE).strength(1.5F, 6.0F).requiresCorrectToolForDrops()));
    public static final RegistryObject<Block> AMBER = registerBlock("amber", () -> new AmethystClusterBlock(4, 2, BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(1.0f).sound(SoundType.GLASS).lightLevel(value -> 7)));
    public static final RegistryObject<Block> AMBER_BLOCK = registerBlock("amber_block", () -> new Block(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(1.0f).sound(SoundType.GLASS).lightLevel(value -> 7)));
    public static final RegistryObject<Block> CRYSTAL_MELON = registerBlock("crystal_melon", () -> new CrystalMelon(BlockBehaviour.Properties.of().strength(0.3F, 0.6F).sound(SoundType.GLASS).lightLevel(value -> 10)));
    public static final RegistryObject<Block> PETRIFIED_SIGN = registerNoTabBlock("petrified_sign", () -> new DDStandingSignBlock(BlockBehaviour.Properties.of().noCollission().strength(1.0F).requiresCorrectToolForDrops().sound(SoundType.WOOD), DDWoodType.PETRIFIED));
    public static final RegistryObject<Block> PETRIFIED_WALL_SIGN = registerNoTabBlock("petrified_wall_sign", () -> new DDWallSignBlock(BlockBehaviour.Properties.of().noCollission().strength(1.0F).requiresCorrectToolForDrops().sound(SoundType.WOOD), DDWoodType.PETRIFIED));
    public static final RegistryObject<Block> GEYSER = registerBlock("geyser", () -> new GeyserBlock(BlockBehaviour.Properties.of().strength(1.5F, 6.0F).requiresCorrectToolForDrops().randomTicks()));
    public static final RegistryObject<Block> PETRIFIED_PRESSURE_PLATE = registerBlock("petrified_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING ,Block.Properties.of().requiresCorrectToolForDrops().strength(0.5f).sound(SoundType.WOOD), DDBlockSetTypes.PETRIFIED));
    public static final RegistryObject<Block> PETRIFIED_TRAPDOOR = registerBlock("petrified_trapdoor", () -> new TrapDoorBlock(Block.Properties.of().requiresCorrectToolForDrops().noOcclusion().strength(2.5f, 3.0f).sound(SoundType.WOOD), DDBlockSetTypes.PETRIFIED));
    public static final RegistryObject<Block> PETRIFIED_FENCE_GATE = registerBlock("petrified_fence_gate", () -> new FenceGateBlock(Block.Properties.of().requiresCorrectToolForDrops().strength(2.5f, 3.0f).sound(SoundType.WOOD), DDWoodType.PETRIFIED));
    public static final RegistryObject<Block> PETRIFIED_BUTTON = registerBlock("petrified_button", () -> new ButtonBlock(Block.Properties.of().requiresCorrectToolForDrops().strength(0.5f).sound(SoundType.WOOD), DDBlockSetTypes.PETRIFIED, 30, true));
    public static final RegistryObject<Block> PETRIFIED_DOOR = registerBlock("petrified_door", () -> new DoorBlock(Block.Properties.of().requiresCorrectToolForDrops().noOcclusion().strength(2.5f, 3.0f).sound(SoundType.WOOD), DDBlockSetTypes.PETRIFIED));
    public static final RegistryObject<Block> RAW_SILVER_BLOCK = registerBlock("raw_silver_block", () -> new Block(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(5.0F, 6.0F)));
    public static final RegistryObject<Block> SILVER_BLOCK = registerBlock("silver_block", () -> new Block(BlockBehaviour.Properties.of().requiresCorrectToolForDrops().strength(5.0F, 6.0F).sound(SoundType.METAL)));
    public static final RegistryObject<Block> DEATH_ANCHOR = registerBlock("death_anchor", () -> new Block(BlockBehaviour.Properties.of().sound(SoundType.NETHER_BRICKS)));
    public static final RegistryObject<Block> ARID_DEEPSLATE = registerBlock("arid_deepslate", () -> new LayeredDeepslateBlock(BlockBehaviour.Properties.copy(Blocks.DEEPSLATE).randomTicks()));
    public static final RegistryObject<Block> GLOWSHROOM_LANTERN = registerBlock("glowshroom_lantern", () -> new GlowshroomLanternBlock(BlockBehaviour.Properties.copy(Blocks.LANTERN)));
    public static final RegistryObject<Block> GLOWSHROOM_LAMP = registerBlock("glowshroom_lamp", () -> new RedstoneLampBlock(BlockBehaviour.Properties.copy(Blocks.REDSTONE_LAMP)));

    public static <B extends Block> RegistryObject<B> registerBlock(String name, Supplier<? extends B> blocks) {
        RegistryObject<B> block = BLOCKS.register(name, blocks);
        DDItems.ITEMS.register(name, () -> new BlockItem(block.get(), new Item.Properties()));
        return block;
    }

    public static <B extends Block> RegistryObject<B> registerNoTabBlock(String name, Supplier<? extends B> blocks) {
        return BLOCKS.register(name, blocks);
    }

    public static <B extends Block> RegistryObject<B> registerCompatBlock(String modId, String key, Supplier<? extends B> block) {
        RegistryObject<B> blocks = BLOCKS.register(key, block);
        RegistryObject<BlockItem> item = DDItems.ITEMS.register(key, () -> new BlockItem(blocks.get(), new Item.Properties()));
        COMPAT.put(item, modId);
        return blocks;
    }

}