package com.naterbobber.darkerdepths.block.blocksets;

import com.naterbobber.darkerdepths.init.DDBlocks;
import com.naterbobber.darkerdepths.init.DDItems;
import com.naterbobber.darkerdepths.util.DDTags;

import java.util.Set;

public class DDBlockSets {
    public static final StoneBlockSet DARKSLATE = StoneBlockSet.builder()
            .base(DDBlocks.DARKSLATE)
            .baseStairs(DDBlocks.DARKSLATE_STAIRS)
            .baseSlab(DDBlocks.DARKSLATE_SLAB)
            .baseVerticalSlab(DDBlocks.DARKSLATE_VERTICAL_SLAB)
            .baseWall(DDBlocks.DARKSLATE_WALL)
            .polished(DDBlocks.POLISHED_DARKSLATE)
            .polishedSlab(DDBlocks.POLISHED_DARKSLATE_SLAB)
            .polishedVerticalSlab(DDBlocks.POLISHED_DARKSLATE_VERTICAL_SLAB)
            .polishedStairs(DDBlocks.POLISHED_DARKSLATE_STAIRS)
            .bricks(DDBlocks.DARKSLATE_BRICKS)
            .bricksStairs(DDBlocks.DARKSLATE_BRICKS_STAIRS)
            .bricksSlab(DDBlocks.DARKSLATE_BRICKS_SLAB)
            .bricksVerticalSlab(DDBlocks.DARKSLATE_BRICKS_VERTICAL_SLAB)
            .bricksWall(DDBlocks.DARKSLATE_BRICKS_WALL)
            .chiseled(DDBlocks.CHISELED_DARKSLATE_BRICKS)
            .crackedBricks(DDBlocks.CRACKED_DARKSLATE_BRICKS)
            .pillar(DDBlocks.DARKSLATE_PILLAR)
            .build();

    public static final StoneBlockSet ARIDROCK = StoneBlockSet.builder()
            .base(DDBlocks.ARIDROCK)
            .baseStairs(DDBlocks.ARIDROCK_STAIRS)
            .baseSlab(DDBlocks.ARIDROCK_SLAB)
            .baseVerticalSlab(DDBlocks.ARIDROCK_VERTICAL_SLAB)
            .baseWall(DDBlocks.ARIDROCK_WALL)
            .polished(DDBlocks.POLISHED_ARIDROCK)
            .polishedSlab(DDBlocks.POLISHED_ARIDROCK_SLAB)
            .polishedVerticalSlab(DDBlocks.POLISHED_ARIDROCK_VERTICAL_SLAB)
            .polishedStairs(DDBlocks.POLISHED_ARIDROCK_STAIRS)
            .bricks(DDBlocks.ARIDROCK_BRICKS)
            .bricksStairs(DDBlocks.ARIDROCK_BRICKS_STAIRS)
            .bricksSlab(DDBlocks.ARIDROCK_BRICKS_SLAB)
            .bricksVerticalSlab(DDBlocks.ARIDROCK_BRICKS_VERTICAL_SLAB)
            .bricksWall(DDBlocks.ARIDROCK_BRICKS_WALL)
            .chiseled(DDBlocks.CHISELED_ARIDROCK_BRICKS)
            .crackedBricks(DDBlocks.CRACKED_ARIDROCK_BRICKS)
            .pillar(DDBlocks.ARIDROCK_PILLAR)
            .build();

    public static final StoneBlockSet DUSKROCK = StoneBlockSet.builder()
            .base(DDBlocks.DUSKROCK)
            .baseStairs(DDBlocks.DUSKROCK_STAIRS)
            .baseSlab(DDBlocks.DUSKROCK_SLAB)
            .baseVerticalSlab(DDBlocks.DUSKROCK_VERTICAL_SLAB)
            .baseWall(DDBlocks.DUSKROCK_WALL)
            .polished(DDBlocks.POLISHED_DUSKROCK)
            .polishedSlab(DDBlocks.POLISHED_DUSKROCK_SLAB)
            .polishedVerticalSlab(DDBlocks.POLISHED_DUSKROCK_VERTICAL_SLAB)
            .polishedStairs(DDBlocks.POLISHED_DUSKROCK_STAIRS)
            .bricks(DDBlocks.DUSKROCK_BRICKS)
            .bricksStairs(DDBlocks.DUSKROCK_BRICKS_STAIRS)
            .bricksSlab(DDBlocks.DUSKROCK_BRICKS_SLAB)
            .bricksVerticalSlab(DDBlocks.DUSKROCK_BRICKS_VERTICAL_SLAB)
            .bricksWall(DDBlocks.DUSKROCK_BRICKS_WALL)
            .chiseled(DDBlocks.CHISELED_DUSKROCK_BRICKS)
            .crackedBricks(DDBlocks.CRACKED_DUSKROCK_BRICKS)
            .pillar(DDBlocks.DUSKROCK_PILLAR)
            .build();

    public static final StoneBlockSet GRIMESTONE = StoneBlockSet.builder()
            .base(DDBlocks.GRIMESTONE)
            .baseStairs(DDBlocks.GRIMESTONE_STAIRS)
            .baseSlab(DDBlocks.GRIMESTONE_SLAB)
            .baseVerticalSlab(DDBlocks.GRIMESTONE_VERTICAL_SLAB)
            .baseWall(DDBlocks.GRIMESTONE_WALL)
            .polished(DDBlocks.POLISHED_GRIMESTONE)
            .polishedSlab(DDBlocks.POLISHED_GRIMESTONE_SLAB)
            .polishedVerticalSlab(DDBlocks.POLISHED_GRIMESTONE_VERTICAL_SLAB)
            .polishedStairs(DDBlocks.POLISHED_GRIMESTONE_STAIRS)
            .bricks(DDBlocks.GRIMESTONE_BRICKS)
            .bricksStairs(DDBlocks.GRIMESTONE_BRICKS_STAIRS)
            .bricksSlab(DDBlocks.GRIMESTONE_BRICKS_SLAB)
            .bricksVerticalSlab(DDBlocks.GRIMESTONE_BRICKS_VERTICAL_SLAB)
            .bricksWall(DDBlocks.GRIMESTONE_BRICKS_WALL)
            .chiseled(DDBlocks.CHISELED_GRIMESTONE_BRICKS)
            .crackedBricks(DDBlocks.CRACKED_GRIMESTONE_BRICKS)
            .mossyBricks(DDBlocks.MOSSY_GRIMESTONE_BRICKS)
            .mossyBricksStairs(DDBlocks.MOSSY_GRIMESTONE_BRICKS_STAIRS)
            .mossyBricksSlab(DDBlocks.MOSSY_GRIMESTONE_BRICKS_SLAB)
            .mossyBricksVerticalSlab(DDBlocks.MOSSY_GRIMESTONE_BRICKS_VERTICAL_SLAB)
            .mossyBricksWall(DDBlocks.MOSSY_GRIMESTONE_BRICKS_WALL)
            .pillar(DDBlocks.GRIMESTONE_PILLAR)
            .build();

    public static final StoneBlockSet GLIST = StoneBlockSet.builder()
            .base(DDBlocks.GLIST)
            .baseStairs(DDBlocks.GLIST_STAIRS)
            .baseSlab(DDBlocks.GLIST_SLAB)
            .baseVerticalSlab(DDBlocks.GLIST_VERTICAL_SLAB)
            .baseWall(DDBlocks.GLIST_WALL)
            .polished(DDBlocks.POLISHED_GLIST)
            .polishedSlab(DDBlocks.POLISHED_GLIST_SLAB)
            .polishedVerticalSlab(DDBlocks.POLISHED_GLIST_VERTICAL_SLAB)
            .polishedStairs(DDBlocks.POLISHED_GLIST_STAIRS)
            .bricks(DDBlocks.GLIST_BRICKS)
            .bricksStairs(DDBlocks.GLIST_BRICKS_STAIRS)
            .bricksSlab(DDBlocks.GLIST_BRICKS_SLAB)
            .bricksVerticalSlab(DDBlocks.GLIST_BRICKS_VERTICAL_SLAB)
            .bricksWall(DDBlocks.GLIST_BRICKS_WALL)
            .chiseled(DDBlocks.CHISELED_GLIST_BRICKS)
            .crackedBricks(DDBlocks.CRACKED_GLIST_BRICKS)
            .pillar(DDBlocks.GLIST_PILLAR)
            .build();

    public static final WoodBlockSet PETRIFIED = WoodBlockSet.builder()
            .log(DDBlocks.PETRIFIED_LOG)
            .wood(DDBlocks.PETRIFIED_WOOD)
            .strippedLog(DDBlocks.STRIPPED_PETRIFIED_LOG)
            .strippedWood(DDBlocks.STRIPPED_PETRIFIED_WOOD)
            .planks(DDBlocks.PETRIFIED_PLANKS)
            .boards(DDBlocks.PETRIFIED_BOARDS)
            .verticalPlanks(DDBlocks.VERTICAL_PETRIFIED_PLANKS)
            .stairs(DDBlocks.PETRIFIED_STAIRS)
            .slab(DDBlocks.PETRIFIED_SLAB)
            .verticalSlab(DDBlocks.PETRIFIED_VERTICAL_SLAB)
            .trimmedPlanks(DDBlocks.TRIMMED_PETRIFIED_PLANKS)
            .fence(DDBlocks.PETRIFIED_FENCE)
            .fenceGate(DDBlocks.PETRIFIED_FENCE_GATE)
            .door(DDBlocks.PETRIFIED_DOOR)
            .trapdoor(DDBlocks.PETRIFIED_TRAPDOOR)
            .bookshelf(DDBlocks.PETRIFIED_BOOKSHELF)
            .pressurePlate(DDBlocks.PETRIFIED_PRESSURE_PLATE)
            .button(DDBlocks.PETRIFIED_BUTTON)
            .sign(DDBlocks.PETRIFIED_SIGN)
            .wallSign(DDBlocks.PETRIFIED_WALL_SIGN)
            .hangingSign(DDBlocks.PETRIFIED_HANGING_SIGN)
            .wallHangingSign(DDBlocks.PETRIFIED_WALL_HANGING_SIGN)
            .post(DDBlocks.PETRIFIED_POST)
            .strippedPost(DDBlocks.STRIPPED_PETRIFIED_POST)
            .boat(DDItems.PETRIFIED_BOAT)
            .chestBoat(DDItems.PETRIFIED_CHEST_BOAT)
            .logTag(DDTags.Items.PETRIFIED_LOGS)
            .build();

    public static final WoodBlockSet GLOWSHROOM = WoodBlockSet.builder()
            .log(DDBlocks.GLOWSHROOM_STEM)
            .wood(DDBlocks.GLOWSHROOM_HYPHAE)
            .strippedLog(DDBlocks.STRIPPED_GLOWSHROOM_STEM)
            .strippedWood(DDBlocks.STRIPPED_GLOWSHROOM_HYPHAE)
            .planks(DDBlocks.GLOWSHROOM_PLANKS)
            .boards(DDBlocks.GLOWSHROOM_BOARDS)
            .verticalPlanks(DDBlocks.VERTICAL_GLOWSHROOM_PLANKS)
            .stairs(DDBlocks.GLOWSHROOM_STAIRS)
            .slab(DDBlocks.GLOWSHROOM_SLAB)
            .verticalSlab(DDBlocks.GLOWSHROOM_VERTICAL_SLAB)
            .trimmedPlanks(DDBlocks.TRIMMED_GLOWSHROOM_PLANKS)
            .fence(DDBlocks.GLOWSHROOM_FENCE)
            .fenceGate(DDBlocks.GLOWSHROOM_FENCE_GATE)
            .door(DDBlocks.GLOWSHROOM_DOOR)
            .trapdoor(DDBlocks.GLOWSHROOM_TRAPDOOR)
            .bookshelf(DDBlocks.GLOWSHROOM_BOOKSHELF)
            .pressurePlate(DDBlocks.GLOWSHROOM_PRESSURE_PLATE)
            .button(DDBlocks.GLOWSHROOM_BUTTON)
            .sign(DDBlocks.GLOWSHROOM_SIGN)
            .wallSign(DDBlocks.GLOWSHROOM_WALL_SIGN)
            .hangingSign(DDBlocks.GLOWSHROOM_HANGING_SIGN)
            .wallHangingSign(DDBlocks.GLOWSHROOM_WALL_HANGING_SIGN)
            .post(DDBlocks.GLOWSHROOM_POST)
            .strippedPost(DDBlocks.STRIPPED_GLOWSHROOM_POST)
            .boat(DDItems.GLOWSHROOM_BOAT)
            .chestBoat(DDItems.GLOWSHROOM_CHEST_BOAT)
            .logTag(DDTags.Items.GLOWSHROOM_STEMS)
            .build();

    public static final Set<StoneBlockSet> STONE_BLOCK_SETS = Set.of(
            DARKSLATE,
            ARIDROCK,
            DUSKROCK,
            GRIMESTONE,
            GLIST
    );

    public static final Set<WoodBlockSet> WOOD_BLOCK_SETS = Set.of(
            PETRIFIED,
            GLOWSHROOM
    );
}